# Generated by Django 5.2.11 on 2026-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('vehicles', 'Vehicles'), ('appliances', 'Appliances'), ('books', 'Books'), ('fashion', 'Fashion')], default='electronics', max_length=50),
        ),
    ]
