# Generated by Django 5.2.9 on 2026-03-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('money', 'Money'), ('barter', 'Barter'), ('both', 'Both (Money + Barter)')], default='barter', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_deals', to='products.product'),
        ),
    ]
